/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuestRouteImport } from './routes/guest'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppScrapeRouteImport } from './routes/app.scrape'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppJobJobIdRouteImport } from './routes/app.job.$jobId'
import { Route as AppAiJobIdRouteImport } from './routes/app.ai.$jobId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/guest',
  path: '/guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppScrapeRoute = AppScrapeRouteImport.update({
  id: '/scrape',
  path: '/scrape',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppJobJobIdRoute = AppJobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => AppRoute,
} as any)
const AppAiJobIdRoute = AppAiJobIdRouteImport.update({
  id: '/ai/$jobId',
  path: '/ai/$jobId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/scrape': typeof AppScrapeRoute
  '/app/': typeof AppIndexRoute
  '/app/ai/$jobId': typeof AppAiJobIdRoute
  '/app/job/$jobId': typeof AppJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/scrape': typeof AppScrapeRoute
  '/app': typeof AppIndexRoute
  '/app/ai/$jobId': typeof AppAiJobIdRoute
  '/app/job/$jobId': typeof AppJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/guest': typeof GuestRoute
  '/login': typeof LoginRoute
  '/app/billing': typeof AppBillingRoute
  '/app/history': typeof AppHistoryRoute
  '/app/scrape': typeof AppScrapeRoute
  '/app/': typeof AppIndexRoute
  '/app/ai/$jobId': typeof AppAiJobIdRoute
  '/app/job/$jobId': typeof AppJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/guest'
    | '/login'
    | '/app/billing'
    | '/app/history'
    | '/app/scrape'
    | '/app/'
    | '/app/ai/$jobId'
    | '/app/job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guest'
    | '/login'
    | '/app/billing'
    | '/app/history'
    | '/app/scrape'
    | '/app'
    | '/app/ai/$jobId'
    | '/app/job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/guest'
    | '/login'
    | '/app/billing'
    | '/app/history'
    | '/app/scrape'
    | '/app/'
    | '/app/ai/$jobId'
    | '/app/job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest': {
      id: '/guest'
      path: '/guest'
      fullPath: '/guest'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scrape': {
      id: '/app/scrape'
      path: '/scrape'
      fullPath: '/app/scrape'
      preLoaderRoute: typeof AppScrapeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/job/$jobId': {
      id: '/app/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/app/job/$jobId'
      preLoaderRoute: typeof AppJobJobIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai/$jobId': {
      id: '/app/ai/$jobId'
      path: '/ai/$jobId'
      fullPath: '/app/ai/$jobId'
      preLoaderRoute: typeof AppAiJobIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppScrapeRoute: typeof AppScrapeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAiJobIdRoute: typeof AppAiJobIdRoute
  AppJobJobIdRoute: typeof AppJobJobIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppScrapeRoute: AppScrapeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAiJobIdRoute: AppAiJobIdRoute,
  AppJobJobIdRoute: AppJobJobIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
